version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "9229:9229"

    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    depends_on:
      - db
      - redis

volumes:  
  db-data:  
  redis-data:
  node_modules: 